### ISSUE TITLE
individual course pages

### ISSUE THREAD

**Issue by Nitrostrider** [ericzhu105/academia-site#69]
1.) Make individual course pages for each course (I timed how long it took me to do this for Scratch and it was around 25 minutes so its not easy task)

**Comment by Nitrostrider** [comment]
the styling for images using col-lg-3 is wrong, change it to based on number of teachers

**Comment by Nitrostrider** [comment]
title tages for all the course html files

**Comment by RaghavSriram72** [comment]
Yes, I timed myself as well. Making individual course pages is no easy task.

**Comment by Nitrostrider** [comment]
Summary of what to do:
 - Update dropdown links 
   - Set navdropdownactive
   - delete class="active"for the index file in navbar
   - add "intro to game development" at bootom of dropdown
   - delete "intro to game dev"in dropdown
 - Add "end time" to both mobile and desktop version of table
 - Profile pictures
 - Course description
 - Links to each teachers github, email, ect.
 - <title></title>
 - check to see if mailto: is there for mail links
 - check indenting
 - if you're on mac use shift+option+f to resize the indenting on the page
