### ISSUE TITLE
joinus template

### ISSUE THREAD

**Issue by Nitrostrider** [ericzhu105/academia-site#80]
See eamon's google doc

**Comment by ghost** [comment]
1. Replace paragraph tags with lists
2. Changing font of paragraphs
3. Add background to columns
4. Create another row
5. Remove border
6. Center everything
7. Creating padding between title, paragraph, and columns

**Comment by Nitrostrider** [comment]
Also margins and putting more space between the two columns

**Comment by Nitrostrider** [comment]
The title wording
